# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_w.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1538, 883)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setBaseSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/logo"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(790, 500))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_soa = QtWidgets.QWidget()
        self.tab_soa.setObjectName("tab_soa")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_soa)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox2 = QtWidgets.QGroupBox(self.tab_soa)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        self.groupBox2.setMinimumSize(QtCore.QSize(1200, 200))
        self.groupBox2.setBaseSize(QtCore.QSize(400, 300))
        self.groupBox2.setObjectName("groupBox2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 289, 125))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ln_soa_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.ln_soa_id.setObjectName("ln_soa_id")
        self.gridLayout.addWidget(self.ln_soa_id, 2, 1, 1, 2)
        self.ln_soa_cf = QtWidgets.QLineEdit(self.layoutWidget)
        self.ln_soa_cf.setObjectName("ln_soa_cf")
        self.gridLayout.addWidget(self.ln_soa_cf, 1, 1, 1, 2)
        self.lb_soa_id = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_soa_id.setFont(font)
        self.lb_soa_id.setObjectName("lb_soa_id")
        self.gridLayout.addWidget(self.lb_soa_id, 2, 0, 1, 1)
        self.lb_soa_cf = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        self.lb_soa_cf.setFont(font)
        self.lb_soa_cf.setObjectName("lb_soa_cf")
        self.gridLayout.addWidget(self.lb_soa_cf, 1, 0, 1, 1)
        self.lb_soa_cf_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        self.lb_soa_cf_2.setFont(font)
        self.lb_soa_cf_2.setObjectName("lb_soa_cf_2")
        self.gridLayout.addWidget(self.lb_soa_cf_2, 0, 0, 1, 1)
        self.ln_soa_impresa = QtWidgets.QLineEdit(self.layoutWidget)
        self.ln_soa_impresa.setObjectName("ln_soa_impresa")
        self.gridLayout.addWidget(self.ln_soa_impresa, 0, 1, 1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox2)
        self.layoutWidget1.setGeometry(QtCore.QRect(320, 40, 267, 125))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lb_soa_stato = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_soa_stato.setFont(font)
        self.lb_soa_stato.setObjectName("lb_soa_stato")
        self.gridLayout_4.addWidget(self.lb_soa_stato, 0, 0, 1, 1)
        self.cb_soa_stato = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_soa_stato.setObjectName("cb_soa_stato")
        self.gridLayout_4.addWidget(self.cb_soa_stato, 0, 1, 1, 3)
        self.lb_soa_riferimenti = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_soa_riferimenti.setFont(font)
        self.lb_soa_riferimenti.setObjectName("lb_soa_riferimenti")
        self.gridLayout_4.addWidget(self.lb_soa_riferimenti, 1, 0, 1, 3)
        self.ln_soa_riferimenti = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ln_soa_riferimenti.setObjectName("ln_soa_riferimenti")
        self.gridLayout_4.addWidget(self.ln_soa_riferimenti, 1, 3, 1, 1)
        self.lb_soa_categoria = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_soa_categoria.setFont(font)
        self.lb_soa_categoria.setObjectName("lb_soa_categoria")
        self.gridLayout_4.addWidget(self.lb_soa_categoria, 2, 0, 1, 2)
        self.cb_soa_categoria = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_soa_categoria.setObjectName("cb_soa_categoria")
        self.gridLayout_4.addWidget(self.cb_soa_categoria, 2, 2, 1, 2)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox2)
        self.layoutWidget2.setGeometry(QtCore.QRect(610, 40, 353, 125))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lb_soa_prov = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_soa_prov.setFont(font)
        self.lb_soa_prov.setObjectName("lb_soa_prov")
        self.gridLayout_5.addWidget(self.lb_soa_prov, 0, 0, 1, 1)
        self.ln_soa_prov = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ln_soa_prov.setObjectName("ln_soa_prov")
        self.gridLayout_5.addWidget(self.ln_soa_prov, 0, 1, 1, 2)
        self.lb_soa_da = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        self.lb_soa_da.setFont(font)
        self.lb_soa_da.setObjectName("lb_soa_da")
        self.gridLayout_5.addWidget(self.lb_soa_da, 0, 3, 1, 1)
        self.data_soa_da = QtWidgets.QDateEdit(self.layoutWidget2)
        self.data_soa_da.setCalendarPopup(True)
        self.data_soa_da.setDate(QtCore.QDate(2001, 1, 1))
        self.data_soa_da.setObjectName("data_soa_da")
        self.gridLayout_5.addWidget(self.data_soa_da, 0, 4, 1, 1)
        self.lb_soa_a = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        self.lb_soa_a.setFont(font)
        self.lb_soa_a.setObjectName("lb_soa_a")
        self.gridLayout_5.addWidget(self.lb_soa_a, 1, 3, 1, 1)
        self.data_soa_a = QtWidgets.QDateEdit(self.layoutWidget2)
        self.data_soa_a.setCalendarPopup(True)
        self.data_soa_a.setObjectName("data_soa_a")
        self.gridLayout_5.addWidget(self.data_soa_a, 1, 4, 1, 1)
        self.lb_soa_classifica = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_soa_classifica.setFont(font)
        self.lb_soa_classifica.setObjectName("lb_soa_classifica")
        self.gridLayout_5.addWidget(self.lb_soa_classifica, 2, 0, 1, 2)
        self.cb_soa_classifica = QtWidgets.QComboBox(self.layoutWidget2)
        self.cb_soa_classifica.setObjectName("cb_soa_classifica")
        self.gridLayout_5.addWidget(self.cb_soa_classifica, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 2, 4, 1, 1)
        self.lb_soa_comune = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_soa_comune.setFont(font)
        self.lb_soa_comune.setObjectName("lb_soa_comune")
        self.gridLayout_5.addWidget(self.lb_soa_comune, 1, 0, 1, 1)
        self.ln_soa_comune = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ln_soa_comune.setObjectName("ln_soa_comune")
        self.gridLayout_5.addWidget(self.ln_soa_comune, 1, 1, 1, 2)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(1000, 20, 185, 176))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.bt_soa_resetta_filtro = QtWidgets.QPushButton(self.layoutWidget_5)
        self.bt_soa_resetta_filtro.setObjectName("bt_soa_resetta_filtro")
        self.gridLayout_13.addWidget(self.bt_soa_resetta_filtro, 1, 0, 1, 1)
        self.bt_soa_cerca = QtWidgets.QPushButton(self.layoutWidget_5)
        self.bt_soa_cerca.setObjectName("bt_soa_cerca")
        self.gridLayout_13.addWidget(self.bt_soa_cerca, 2, 0, 1, 1)
        self.bt_soa_stampa = QtWidgets.QPushButton(self.layoutWidget_5)
        self.bt_soa_stampa.setObjectName("bt_soa_stampa")
        self.gridLayout_13.addWidget(self.bt_soa_stampa, 3, 0, 1, 1)
        self.bt_soa_nuova_impresa = QtWidgets.QPushButton(self.layoutWidget_5)
        self.bt_soa_nuova_impresa.setObjectName("bt_soa_nuova_impresa")
        self.gridLayout_13.addWidget(self.bt_soa_nuova_impresa, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox2, 0, 0, 1, 1)
        self.tbl_soa_main = QtWidgets.QTableWidget(self.tab_soa)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tbl_soa_main.sizePolicy().hasHeightForWidth())
        self.tbl_soa_main.setSizePolicy(sizePolicy)
        self.tbl_soa_main.setMinimumSize(QtCore.QSize(780, 400))
        self.tbl_soa_main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tbl_soa_main.setFont(font)
        self.tbl_soa_main.setObjectName("tbl_soa_main")
        self.tbl_soa_main.setColumnCount(8)
        self.tbl_soa_main.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_soa_main.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_soa_main.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_soa_main.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_soa_main.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_soa_main.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_soa_main.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_soa_main.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_soa_main.setHorizontalHeaderItem(7, item)
        self.tbl_soa_main.horizontalHeader().setStretchLastSection(True)
        self.tbl_soa_main.verticalHeader().setVisible(False)
        self.tbl_soa_main.verticalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.tbl_soa_main, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_soa, "")
        self.tab_iso = QtWidgets.QWidget()
        self.tab_iso.setObjectName("tab_iso")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_iso)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox2_2 = QtWidgets.QGroupBox(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2_2.sizePolicy().hasHeightForWidth())
        self.groupBox2_2.setSizePolicy(sizePolicy)
        self.groupBox2_2.setMinimumSize(QtCore.QSize(1200, 200))
        self.groupBox2_2.setBaseSize(QtCore.QSize(400, 300))
        self.groupBox2_2.setObjectName("groupBox2_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox2_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 40, 289, 122))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lb_iso_impresa = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_iso_impresa.setFont(font)
        self.lb_iso_impresa.setObjectName("lb_iso_impresa")
        self.gridLayout_8.addWidget(self.lb_iso_impresa, 0, 0, 1, 2)
        self.ln_iso_impresa = QtWidgets.QLineEdit(self.layoutWidget3)
        self.ln_iso_impresa.setObjectName("ln_iso_impresa")
        self.gridLayout_8.addWidget(self.ln_iso_impresa, 0, 2, 1, 1)
        self.lb_iso_cf = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        self.lb_iso_cf.setFont(font)
        self.lb_iso_cf.setObjectName("lb_iso_cf")
        self.gridLayout_8.addWidget(self.lb_iso_cf, 1, 0, 1, 1)
        self.ln_iso_cf = QtWidgets.QLineEdit(self.layoutWidget3)
        self.ln_iso_cf.setObjectName("ln_iso_cf")
        self.gridLayout_8.addWidget(self.ln_iso_cf, 1, 1, 1, 2)
        self.lb_iso_id = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_iso_id.setFont(font)
        self.lb_iso_id.setObjectName("lb_iso_id")
        self.gridLayout_8.addWidget(self.lb_iso_id, 2, 0, 1, 1)
        self.ln_iso_id = QtWidgets.QLineEdit(self.layoutWidget3)
        self.ln_iso_id.setObjectName("ln_iso_id")
        self.gridLayout_8.addWidget(self.ln_iso_id, 2, 1, 1, 2)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox2_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(1000, 20, 185, 172))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.bt_iso_resetta_filtro = QtWidgets.QPushButton(self.layoutWidget_4)
        self.bt_iso_resetta_filtro.setObjectName("bt_iso_resetta_filtro")
        self.gridLayout_11.addWidget(self.bt_iso_resetta_filtro, 1, 0, 1, 1)
        self.bt_iso_cerca = QtWidgets.QPushButton(self.layoutWidget_4)
        self.bt_iso_cerca.setObjectName("bt_iso_cerca")
        self.gridLayout_11.addWidget(self.bt_iso_cerca, 2, 0, 1, 1)
        self.bt_iso_stampa = QtWidgets.QPushButton(self.layoutWidget_4)
        self.bt_iso_stampa.setObjectName("bt_iso_stampa")
        self.gridLayout_11.addWidget(self.bt_iso_stampa, 3, 0, 1, 1)
        self.bt_iso_nuova_impresa = QtWidgets.QPushButton(self.layoutWidget_4)
        self.bt_iso_nuova_impresa.setObjectName("bt_iso_nuova_impresa")
        self.gridLayout_11.addWidget(self.bt_iso_nuova_impresa, 0, 0, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox2_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(320, 40, 261, 122))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lb_iso_stato = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_iso_stato.setFont(font)
        self.lb_iso_stato.setObjectName("lb_iso_stato")
        self.gridLayout_9.addWidget(self.lb_iso_stato, 0, 0, 1, 1)
        self.cb_iso_stato = QtWidgets.QComboBox(self.layoutWidget4)
        self.cb_iso_stato.setObjectName("cb_iso_stato")
        self.gridLayout_9.addWidget(self.cb_iso_stato, 0, 1, 1, 2)
        self.lb_iso_riferimenti = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_iso_riferimenti.setFont(font)
        self.lb_iso_riferimenti.setObjectName("lb_iso_riferimenti")
        self.gridLayout_9.addWidget(self.lb_iso_riferimenti, 1, 0, 1, 2)
        self.ln_iso_riferimenti = QtWidgets.QLineEdit(self.layoutWidget4)
        self.ln_iso_riferimenti.setObjectName("ln_iso_riferimenti")
        self.gridLayout_9.addWidget(self.ln_iso_riferimenti, 1, 2, 1, 1)
        self.lb_iso_prov = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_iso_prov.setFont(font)
        self.lb_iso_prov.setObjectName("lb_iso_prov")
        self.gridLayout_9.addWidget(self.lb_iso_prov, 2, 0, 1, 2)
        self.ln_iso_prov = QtWidgets.QLineEdit(self.layoutWidget4)
        self.ln_iso_prov.setObjectName("ln_iso_prov")
        self.gridLayout_9.addWidget(self.ln_iso_prov, 2, 2, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox2_2, 0, 0, 1, 1)
        self.tbl_iso_main = QtWidgets.QTableWidget(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tbl_iso_main.sizePolicy().hasHeightForWidth())
        self.tbl_iso_main.setSizePolicy(sizePolicy)
        self.tbl_iso_main.setMinimumSize(QtCore.QSize(780, 400))
        self.tbl_iso_main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tbl_iso_main.setFont(font)
        self.tbl_iso_main.setObjectName("tbl_iso_main")
        self.tbl_iso_main.setColumnCount(13)
        self.tbl_iso_main.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_iso_main.setHorizontalHeaderItem(12, item)
        self.tbl_iso_main.horizontalHeader().setStretchLastSection(True)
        self.tbl_iso_main.verticalHeader().setVisible(False)
        self.tbl_iso_main.verticalHeader().setStretchLastSection(True)
        self.gridLayout_12.addWidget(self.tbl_iso_main, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_iso, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1538, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuVista = QtWidgets.QMenu(self.menubar)
        self.menuVista.setObjectName("menuVista")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDatabase = QtWidgets.QAction(MainWindow)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionNuova_Impresa = QtWidgets.QAction(MainWindow)
        self.actionNuova_Impresa.setObjectName("actionNuova_Impresa")
        self.actionFull_Screen = QtWidgets.QAction(MainWindow)
        self.actionFull_Screen.setObjectName("actionFull_Screen")
        self.actionModifica = QtWidgets.QAction(MainWindow)
        self.actionModifica.setObjectName("actionModifica")
        self.menuFile.addAction(self.actionDatabase)
        self.menuFile.addAction(self.actionNuova_Impresa)
        self.menuVista.addAction(self.actionFull_Screen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuVista.menuAction())
        self.lb_soa_da.setBuddy(self.data_soa_da)
        self.lb_soa_a.setBuddy(self.data_soa_a)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.bt_iso_resetta_filtro.clicked.connect(self.ln_iso_riferimenti.clear)
        self.bt_iso_resetta_filtro.clicked.connect(self.ln_iso_prov.clear)
        self.bt_iso_resetta_filtro.clicked.connect(self.ln_iso_impresa.clear)
        self.bt_iso_resetta_filtro.clicked.connect(self.ln_iso_cf.clear)
        self.bt_iso_resetta_filtro.clicked.connect(self.ln_iso_id.clear)
        self.bt_iso_resetta_filtro.clicked.connect(self.cb_iso_stato.clear)
        self.bt_soa_resetta_filtro.clicked.connect(self.ln_soa_impresa.clear)
        self.bt_soa_resetta_filtro.clicked.connect(self.ln_soa_cf.clear)
        self.bt_soa_resetta_filtro.clicked.connect(self.ln_soa_id.clear)
        self.bt_soa_resetta_filtro.clicked.connect(self.ln_soa_riferimenti.clear)
        self.bt_soa_resetta_filtro.clicked.connect(self.ln_soa_prov.clear)
        self.bt_soa_resetta_filtro.clicked.connect(self.ln_soa_comune.clear)
        self.bt_soa_resetta_filtro.pressed.connect(self.cb_soa_stato.clear)
        self.bt_soa_resetta_filtro.pressed.connect(self.cb_soa_categoria.clear)
        self.bt_soa_resetta_filtro.pressed.connect(self.cb_soa_classifica.clear)
        self.ln_soa_cf.returnPressed.connect(self.bt_soa_cerca.click)
        self.ln_soa_id.returnPressed.connect(self.bt_soa_cerca.click)
        self.ln_soa_impresa.returnPressed.connect(self.bt_soa_cerca.click)
        self.ln_soa_riferimenti.returnPressed.connect(self.bt_soa_cerca.click)
        self.ln_soa_prov.returnPressed.connect(self.bt_soa_cerca.click)
        self.ln_soa_comune.returnPressed.connect(self.bt_soa_cerca.click)
        self.ln_iso_impresa.returnPressed.connect(self.bt_iso_cerca.click)
        self.ln_iso_cf.returnPressed.connect(self.bt_iso_cerca.click)
        self.ln_iso_id.returnPressed.connect(self.bt_iso_cerca.click)
        self.ln_iso_riferimenti.returnPressed.connect(self.bt_iso_cerca.click)
        self.ln_iso_prov.returnPressed.connect(self.bt_iso_cerca.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ln_soa_impresa, self.cb_soa_stato)
        MainWindow.setTabOrder(self.cb_soa_stato, self.ln_soa_prov)
        MainWindow.setTabOrder(self.ln_soa_prov, self.data_soa_da)
        MainWindow.setTabOrder(self.data_soa_da, self.ln_soa_cf)
        MainWindow.setTabOrder(self.ln_soa_cf, self.ln_soa_riferimenti)
        MainWindow.setTabOrder(self.ln_soa_riferimenti, self.ln_soa_comune)
        MainWindow.setTabOrder(self.ln_soa_comune, self.data_soa_a)
        MainWindow.setTabOrder(self.data_soa_a, self.ln_soa_id)
        MainWindow.setTabOrder(self.ln_soa_id, self.cb_soa_categoria)
        MainWindow.setTabOrder(self.cb_soa_categoria, self.cb_soa_classifica)
        MainWindow.setTabOrder(self.cb_soa_classifica, self.tbl_soa_main)
        MainWindow.setTabOrder(self.tbl_soa_main, self.bt_soa_nuova_impresa)
        MainWindow.setTabOrder(self.bt_soa_nuova_impresa, self.bt_soa_resetta_filtro)
        MainWindow.setTabOrder(self.bt_soa_resetta_filtro, self.bt_soa_cerca)
        MainWindow.setTabOrder(self.bt_soa_cerca, self.bt_soa_stampa)
        MainWindow.setTabOrder(self.bt_soa_stampa, self.ln_iso_impresa)
        MainWindow.setTabOrder(self.ln_iso_impresa, self.cb_iso_stato)
        MainWindow.setTabOrder(self.cb_iso_stato, self.ln_iso_cf)
        MainWindow.setTabOrder(self.ln_iso_cf, self.ln_iso_riferimenti)
        MainWindow.setTabOrder(self.ln_iso_riferimenti, self.ln_iso_id)
        MainWindow.setTabOrder(self.ln_iso_id, self.ln_iso_prov)
        MainWindow.setTabOrder(self.ln_iso_prov, self.tbl_iso_main)
        MainWindow.setTabOrder(self.tbl_iso_main, self.bt_iso_nuova_impresa)
        MainWindow.setTabOrder(self.bt_iso_nuova_impresa, self.bt_iso_resetta_filtro)
        MainWindow.setTabOrder(self.bt_iso_resetta_filtro, self.bt_iso_cerca)
        MainWindow.setTabOrder(self.bt_iso_cerca, self.bt_iso_stampa)
        MainWindow.setTabOrder(self.bt_iso_stampa, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestione Imprese"))
        self.groupBox2.setTitle(_translate("MainWindow", "Filtri"))
        self.lb_soa_id.setText(_translate("MainWindow", "ID:"))
        self.lb_soa_cf.setText(_translate("MainWindow", "CF:"))
        self.lb_soa_cf_2.setText(_translate("MainWindow", "Impresa:"))
        self.lb_soa_stato.setText(_translate("MainWindow", "Stato:"))
        self.lb_soa_riferimenti.setText(_translate("MainWindow", "Riferimenti:"))
        self.lb_soa_categoria.setText(_translate("MainWindow", "Categoria:"))
        self.lb_soa_prov.setText(_translate("MainWindow", "Prov:"))
        self.lb_soa_da.setText(_translate("MainWindow", "&da:"))
        self.lb_soa_a.setText(_translate("MainWindow", "a:"))
        self.lb_soa_classifica.setText(_translate("MainWindow", "Classifica:"))
        self.lb_soa_comune.setText(_translate("MainWindow", "Comune:"))
        self.bt_soa_resetta_filtro.setText(_translate("MainWindow", "Resetta filtro"))
        self.bt_soa_cerca.setText(_translate("MainWindow", "Cerca"))
        self.bt_soa_stampa.setText(_translate("MainWindow", "Stampa"))
        self.bt_soa_nuova_impresa.setText(_translate("MainWindow", "Nuova Impresa"))
        self.tbl_soa_main.setSortingEnabled(False)
        item = self.tbl_soa_main.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tbl_soa_main.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "RagioneSociale"))
        item = self.tbl_soa_main.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prov"))
        item = self.tbl_soa_main.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Comune"))
        item = self.tbl_soa_main.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Scadenza"))
        item = self.tbl_soa_main.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tipo"))
        item = self.tbl_soa_main.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Stato"))
        item = self.tbl_soa_main.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Riferimenti"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_soa), _translate("MainWindow", "SOA"))
        self.groupBox2_2.setTitle(_translate("MainWindow", "Filtri"))
        self.lb_iso_impresa.setText(_translate("MainWindow", "Impresa:"))
        self.lb_iso_cf.setText(_translate("MainWindow", "CF:"))
        self.lb_iso_id.setText(_translate("MainWindow", "ID:"))
        self.bt_iso_resetta_filtro.setText(_translate("MainWindow", "Resetta Filtro"))
        self.bt_iso_cerca.setText(_translate("MainWindow", "Cerca"))
        self.bt_iso_stampa.setText(_translate("MainWindow", "Stampa"))
        self.bt_iso_nuova_impresa.setText(_translate("MainWindow", "Nuova Impresa"))
        self.lb_iso_stato.setText(_translate("MainWindow", "Stato:"))
        self.lb_iso_riferimenti.setText(_translate("MainWindow", "Riferimenti:"))
        self.lb_iso_prov.setText(_translate("MainWindow", "Prov:"))
        self.tbl_iso_main.setSortingEnabled(False)
        item = self.tbl_iso_main.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tbl_iso_main.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "RagioneSociale"))
        item = self.tbl_iso_main.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prov"))
        item = self.tbl_iso_main.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Comune"))
        item = self.tbl_iso_main.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sc ann 9001"))
        item = self.tbl_iso_main.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sc fin 9001"))
        item = self.tbl_iso_main.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ente_9001"))
        item = self.tbl_iso_main.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sc ann 14001"))
        item = self.tbl_iso_main.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Sc fin 14001"))
        item = self.tbl_iso_main.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Ente_14001"))
        item = self.tbl_iso_main.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Sc ann 18001"))
        item = self.tbl_iso_main.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Sc fin 18001"))
        item = self.tbl_iso_main.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Ente_18001"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_iso), _translate("MainWindow", "ISO"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuVista.setTitle(_translate("MainWindow", "Vi&sta"))
        self.actionDatabase.setText(_translate("MainWindow", "&Database..."))
        self.actionDatabase.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionNuova_Impresa.setText(_translate("MainWindow", "&Nuova Impresa"))
        self.actionNuova_Impresa.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionFull_Screen.setText(_translate("MainWindow", "&Full Screen"))
        self.actionFull_Screen.setToolTip(_translate("MainWindow", "toggleFullScreen"))
        self.actionFull_Screen.setShortcut(_translate("MainWindow", "F11"))
        self.actionModifica.setText(_translate("MainWindow", "Modifica"))


import res_rc
