# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edita_impresa.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1600, 900)
        font = QtGui.QFont()
        font.setPointSize(11)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/logo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(True)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(6, 50, 1600, 850))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_generale = QtWidgets.QWidget()
        self.tab_generale.setObjectName("tab_generale")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_generale)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FF0000")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: #FF0000")
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #FF0000")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.imp__indirizzo_legale = QtWidgets.QLineEdit(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__indirizzo_legale.setFont(font)
        self.imp__indirizzo_legale.setObjectName("imp__indirizzo_legale")
        self.gridLayout_4.addWidget(self.imp__indirizzo_legale, 2, 1, 1, 1)
        self.imp__indirizzo_op = QtWidgets.QLineEdit(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__indirizzo_op.setFont(font)
        self.imp__indirizzo_op.setObjectName("imp__indirizzo_op")
        self.gridLayout_4.addWidget(self.imp__indirizzo_op, 3, 1, 1, 1)
        self.imp__ragione_sociale = QtWidgets.QLineEdit(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__ragione_sociale.setFont(font)
        self.imp__ragione_sociale.setObjectName("imp__ragione_sociale")
        self.gridLayout_4.addWidget(self.imp__ragione_sociale, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #FF0000")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.imp__codice_fiscale = QtWidgets.QLineEdit(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__codice_fiscale.sizePolicy().hasHeightForWidth())
        self.imp__codice_fiscale.setSizePolicy(sizePolicy)
        self.imp__codice_fiscale.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__codice_fiscale.setFont(font)
        self.imp__codice_fiscale.setObjectName("imp__codice_fiscale")
        self.gridLayout_4.addWidget(self.imp__codice_fiscale, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #FF0000")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 4, 0, 1, 1)
        self.imp__tel = QtWidgets.QLineEdit(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__tel.sizePolicy().hasHeightForWidth())
        self.imp__tel.setSizePolicy(sizePolicy)
        self.imp__tel.setMinimumSize(QtCore.QSize(200, 2))
        self.imp__tel.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__tel.setFont(font)
        self.imp__tel.setObjectName("imp__tel")
        self.gridLayout_4.addWidget(self.imp__tel, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #FF0000")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 5, 0, 1, 1)
        self.imp__fax = QtWidgets.QLineEdit(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__fax.sizePolicy().hasHeightForWidth())
        self.imp__fax.setSizePolicy(sizePolicy)
        self.imp__fax.setMinimumSize(QtCore.QSize(200, 2))
        self.imp__fax.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__fax.setFont(font)
        self.imp__fax.setObjectName("imp__fax")
        self.gridLayout_4.addWidget(self.imp__fax, 5, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: #FF0000")
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 6, 0, 1, 1)
        self.imp__website = QtWidgets.QLineEdit(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__website.sizePolicy().hasHeightForWidth())
        self.imp__website.setSizePolicy(sizePolicy)
        self.imp__website.setMinimumSize(QtCore.QSize(200, 2))
        self.imp__website.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__website.setFont(font)
        self.imp__website.setObjectName("imp__website")
        self.gridLayout_4.addWidget(self.imp__website, 6, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.imp__provincia_legale = QtWidgets.QLineEdit(self.tab_generale)
        self.imp__provincia_legale.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__provincia_legale.sizePolicy().hasHeightForWidth())
        self.imp__provincia_legale.setSizePolicy(sizePolicy)
        self.imp__provincia_legale.setMinimumSize(QtCore.QSize(40, 0))
        self.imp__provincia_legale.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__provincia_legale.setFont(font)
        self.imp__provincia_legale.setObjectName("imp__provincia_legale")
        self.gridLayout.addWidget(self.imp__provincia_legale, 2, 3, 1, 1)
        self.imp__pec = QtWidgets.QLineEdit(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__pec.sizePolicy().hasHeightForWidth())
        self.imp__pec.setSizePolicy(sizePolicy)
        self.imp__pec.setMinimumSize(QtCore.QSize(200, 2))
        self.imp__pec.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__pec.setFont(font)
        self.imp__pec.setObjectName("imp__pec")
        self.gridLayout.addWidget(self.imp__pec, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #FF0000")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: #FF0000")
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: #FF0000")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #FF0000")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.imp__provincia_op = QtWidgets.QLineEdit(self.tab_generale)
        self.imp__provincia_op.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__provincia_op.sizePolicy().hasHeightForWidth())
        self.imp__provincia_op.setSizePolicy(sizePolicy)
        self.imp__provincia_op.setMinimumSize(QtCore.QSize(40, 0))
        self.imp__provincia_op.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__provincia_op.setFont(font)
        self.imp__provincia_op.setObjectName("imp__provincia_op")
        self.gridLayout.addWidget(self.imp__provincia_op, 3, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: #FF0000")
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 5, 0, 1, 1)
        self.imp__comune_legale = QtWidgets.QLineEdit(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__comune_legale.sizePolicy().hasHeightForWidth())
        self.imp__comune_legale.setSizePolicy(sizePolicy)
        self.imp__comune_legale.setMinimumSize(QtCore.QSize(200, 2))
        self.imp__comune_legale.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__comune_legale.setFont(font)
        self.imp__comune_legale.setObjectName("imp__comune_legale")
        self.gridLayout.addWidget(self.imp__comune_legale, 2, 1, 1, 1)
        self.imp__comune_op = QtWidgets.QLineEdit(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__comune_op.sizePolicy().hasHeightForWidth())
        self.imp__comune_op.setSizePolicy(sizePolicy)
        self.imp__comune_op.setMinimumSize(QtCore.QSize(200, 2))
        self.imp__comune_op.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__comune_op.setFont(font)
        self.imp__comune_op.setObjectName("imp__comune_op")
        self.gridLayout.addWidget(self.imp__comune_op, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FF0000")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.imp__sdi = QtWidgets.QLineEdit(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__sdi.sizePolicy().hasHeightForWidth())
        self.imp__sdi.setSizePolicy(sizePolicy)
        self.imp__sdi.setMinimumSize(QtCore.QSize(200, 2))
        self.imp__sdi.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__sdi.setFont(font)
        self.imp__sdi.setObjectName("imp__sdi")
        self.gridLayout.addWidget(self.imp__sdi, 4, 1, 1, 1)
        self.imp__email = QtWidgets.QLineEdit(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__email.sizePolicy().hasHeightForWidth())
        self.imp__email.setSizePolicy(sizePolicy)
        self.imp__email.setMinimumSize(QtCore.QSize(200, 2))
        self.imp__email.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__email.setFont(font)
        self.imp__email.setObjectName("imp__email")
        self.gridLayout.addWidget(self.imp__email, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: #FF0000")
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 3, 0, 1, 1)
        self.imp__email2 = QtWidgets.QLineEdit(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__email2.sizePolicy().hasHeightForWidth())
        self.imp__email2.setSizePolicy(sizePolicy)
        self.imp__email2.setMinimumSize(QtCore.QSize(200, 2))
        self.imp__email2.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__email2.setFont(font)
        self.imp__email2.setObjectName("imp__email2")
        self.gridLayout.addWidget(self.imp__email2, 1, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: #FF0000")
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.soa__riferimenti = QtWidgets.QLineEdit(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.soa__riferimenti.setFont(font)
        self.soa__riferimenti.setObjectName("soa__riferimenti")
        self.gridLayout.addWidget(self.soa__riferimenti, 0, 1, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.imp__contatti = QtWidgets.QTableWidget(self.tab_generale)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp__contatti.sizePolicy().hasHeightForWidth())
        self.imp__contatti.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imp__contatti.setFont(font)
        self.imp__contatti.setAutoFillBackground(False)
        self.imp__contatti.setStyleSheet("")
        self.imp__contatti.setObjectName("imp__contatti")
        self.imp__contatti.setColumnCount(5)
        self.imp__contatti.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.imp__contatti.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.imp__contatti.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.imp__contatti.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.imp__contatti.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.imp__contatti.setHorizontalHeaderItem(4, item)
        self.imp__contatti.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.imp__contatti, 1, 0, 1, 2)
        self.label_37 = QtWidgets.QLabel(self.tab_generale)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: #FF0000")
        self.label_37.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_generale, "")
        self.tab_soa = QtWidgets.QWidget()
        self.tab_soa.setObjectName("tab_soa")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_soa)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.tab_soa)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("color:#FF0000")
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.soa__tipo = QtWidgets.QLineEdit(self.tab_soa)
        self.soa__tipo.setEnabled(True)
        self.soa__tipo.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.soa__tipo.setFont(font)
        self.soa__tipo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.soa__tipo.setObjectName("soa__tipo")
        self.gridLayout_2.addWidget(self.soa__tipo, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_soa)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:#FF0000")
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 2, 1, 1)
        self.soa__stato = QtWidgets.QLineEdit(self.tab_soa)
        self.soa__stato.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soa__stato.sizePolicy().hasHeightForWidth())
        self.soa__stato.setSizePolicy(sizePolicy)
        self.soa__stato.setMinimumSize(QtCore.QSize(300, 0))
        self.soa__stato.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.soa__stato.setFont(font)
        self.soa__stato.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.soa__stato.setObjectName("soa__stato")
        self.gridLayout_2.addWidget(self.soa__stato, 0, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_soa)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setStyleSheet("color:#FF0000")
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_soa)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setStyleSheet("color:#FF0000")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 6, 1, 1)
        self.soa__ente = QtWidgets.QLineEdit(self.tab_soa)
        self.soa__ente.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.soa__ente.setFont(font)
        self.soa__ente.setObjectName("soa__ente")
        self.gridLayout_2.addWidget(self.soa__ente, 0, 7, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_soa)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setStyleSheet("color:#FF0000")
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 8, 1, 1)
        self.soa__scadenza = QtWidgets.QLineEdit(self.tab_soa)
        self.soa__scadenza.setObjectName("soa__scadenza")
        self.gridLayout_2.addWidget(self.soa__scadenza, 0, 9, 1, 1)
        self.soa__scad_qualita = QtWidgets.QLineEdit(self.tab_soa)
        self.soa__scad_qualita.setObjectName("soa__scad_qualita")
        self.gridLayout_2.addWidget(self.soa__scad_qualita, 0, 5, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        self.bt_attestato_pdf = QtWidgets.QPushButton(self.tab_soa)
        self.bt_attestato_pdf.setEnabled(False)
        self.bt_attestato_pdf.setObjectName("bt_attestato_pdf")
        self.gridLayout_8.addWidget(self.bt_attestato_pdf, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_soa)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: #FF0000")
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 1, 0, 1, 1)
        self.soa__categorie = QtWidgets.QTableWidget(self.tab_soa)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soa__categorie.sizePolicy().hasHeightForWidth())
        self.soa__categorie.setSizePolicy(sizePolicy)
        self.soa__categorie.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.soa__categorie.setFont(font)
        self.soa__categorie.setAcceptDrops(True)
        self.soa__categorie.setDragEnabled(False)
        self.soa__categorie.setRowCount(10)
        self.soa__categorie.setObjectName("soa__categorie")
        self.soa__categorie.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.soa__categorie.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.soa__categorie.setHorizontalHeaderItem(1, item)
        self.soa__categorie.horizontalHeader().setCascadingSectionResizes(False)
        self.soa__categorie.horizontalHeader().setDefaultSectionSize(45)
        self.gridLayout_8.addWidget(self.soa__categorie, 2, 0, 3, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_16 = QtWidgets.QLabel(self.tab_soa)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(80, 0))
        self.label_16.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: #FF0000")
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.soa__istruttore = QtWidgets.QLineEdit(self.tab_soa)
        self.soa__istruttore.setEnabled(True)
        self.soa__istruttore.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.soa__istruttore.setFont(font)
        self.soa__istruttore.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.soa__istruttore.setObjectName("soa__istruttore")
        self.gridLayout_5.addWidget(self.soa__istruttore, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_soa)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_soa)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: #FF0000")
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 5, 0, 1, 1)
        self.soa__contratti = QtWidgets.QTableWidget(self.tab_soa)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.soa__contratti.setFont(font)
        self.soa__contratti.setAcceptDrops(True)
        self.soa__contratti.setObjectName("soa__contratti")
        self.soa__contratti.setColumnCount(9)
        self.soa__contratti.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.soa__contratti.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.soa__contratti.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.soa__contratti.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.soa__contratti.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.soa__contratti.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.soa__contratti.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.soa__contratti.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.soa__contratti.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.soa__contratti.setHorizontalHeaderItem(8, item)
        self.soa__contratti.horizontalHeader().setDefaultSectionSize(150)
        self.soa__contratti.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.soa__contratti, 6, 0, 1, 3)
        self.soa__add_date = QtWidgets.QPushButton(self.tab_soa)
        self.soa__add_date.setObjectName("soa__add_date")
        self.gridLayout_8.addWidget(self.soa__add_date, 3, 2, 1, 1)
        self.soa__note = QtWidgets.QTextBrowser(self.tab_soa)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.soa__note.setFont(font)
        self.soa__note.setReadOnly(False)
        self.soa__note.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.soa__note.setOpenExternalLinks(True)
        self.soa__note.setObjectName("soa__note")
        self.gridLayout_8.addWidget(self.soa__note, 4, 1, 1, 2)
        self.tabWidget.addTab(self.tab_soa, "")
        self.tab_iso = QtWidgets.QWidget()
        self.tab_iso.setObjectName("tab_iso")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_iso)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_36 = QtWidgets.QLabel(self.tab_iso)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: #FF0000")
        self.label_36.setObjectName("label_36")
        self.gridLayout_10.addWidget(self.label_36, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(335, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 0, 1, 1, 1)
        self.bt_browser_doc = QtWidgets.QPushButton(self.tab_iso)
        self.bt_browser_doc.setObjectName("bt_browser_doc")
        self.gridLayout_10.addWidget(self.bt_browser_doc, 0, 2, 1, 1)
        self.iso__tabel = QtWidgets.QTableWidget(self.tab_iso)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.iso__tabel.setFont(font)
        self.iso__tabel.setObjectName("iso__tabel")
        self.iso__tabel.setColumnCount(11)
        self.iso__tabel.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__tabel.setHorizontalHeaderItem(10, item)
        self.iso__tabel.horizontalHeader().setDefaultSectionSize(130)
        self.iso__tabel.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_10.addWidget(self.iso__tabel, 1, 0, 1, 3)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_24 = QtWidgets.QLabel(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setStyleSheet("color: #FF0000")
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_9.addWidget(self.label_24, 4, 2, 1, 1)
        self.iso__ente_9001 = QtWidgets.QLineEdit(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iso__ente_9001.sizePolicy().hasHeightForWidth())
        self.iso__ente_9001.setSizePolicy(sizePolicy)
        self.iso__ente_9001.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.iso__ente_9001.setFont(font)
        self.iso__ente_9001.setText("")
        self.iso__ente_9001.setObjectName("iso__ente_9001")
        self.gridLayout_9.addWidget(self.iso__ente_9001, 0, 3, 1, 1)
        self.iso__costi9001 = QtWidgets.QTableWidget(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iso__costi9001.sizePolicy().hasHeightForWidth())
        self.iso__costi9001.setSizePolicy(sizePolicy)
        self.iso__costi9001.setMinimumSize(QtCore.QSize(500, 0))
        self.iso__costi9001.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.iso__costi9001.setFont(font)
        self.iso__costi9001.setObjectName("iso__costi9001")
        self.iso__costi9001.setColumnCount(4)
        self.iso__costi9001.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.iso__costi9001.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.iso__costi9001.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.iso__costi9001.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi9001.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi9001.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi9001.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi9001.setHorizontalHeaderItem(3, item)
        self.iso__costi9001.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_9.addWidget(self.iso__costi9001, 1, 0, 1, 4)
        self.iso__costi18001 = QtWidgets.QTableWidget(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iso__costi18001.sizePolicy().hasHeightForWidth())
        self.iso__costi18001.setSizePolicy(sizePolicy)
        self.iso__costi18001.setMinimumSize(QtCore.QSize(500, 0))
        self.iso__costi18001.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.iso__costi18001.setFont(font)
        self.iso__costi18001.setObjectName("iso__costi18001")
        self.iso__costi18001.setColumnCount(4)
        self.iso__costi18001.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.iso__costi18001.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.iso__costi18001.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.iso__costi18001.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi18001.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi18001.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi18001.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi18001.setHorizontalHeaderItem(3, item)
        self.iso__costi18001.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_9.addWidget(self.iso__costi18001, 5, 0, 1, 4)
        self.label_34 = QtWidgets.QLabel(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: #FF0000")
        self.label_34.setObjectName("label_34")
        self.gridLayout_9.addWidget(self.label_34, 4, 0, 1, 1)
        self.iso__ente_18001 = QtWidgets.QLineEdit(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iso__ente_18001.sizePolicy().hasHeightForWidth())
        self.iso__ente_18001.setSizePolicy(sizePolicy)
        self.iso__ente_18001.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.iso__ente_18001.setFont(font)
        self.iso__ente_18001.setText("")
        self.iso__ente_18001.setObjectName("iso__ente_18001")
        self.gridLayout_9.addWidget(self.iso__ente_18001, 4, 3, 1, 1)
        self.iso__costi14001 = QtWidgets.QTableWidget(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iso__costi14001.sizePolicy().hasHeightForWidth())
        self.iso__costi14001.setSizePolicy(sizePolicy)
        self.iso__costi14001.setMinimumSize(QtCore.QSize(500, 0))
        self.iso__costi14001.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.iso__costi14001.setFont(font)
        self.iso__costi14001.setObjectName("iso__costi14001")
        self.iso__costi14001.setColumnCount(4)
        self.iso__costi14001.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.iso__costi14001.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.iso__costi14001.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.iso__costi14001.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi14001.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi14001.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi14001.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.iso__costi14001.setHorizontalHeaderItem(3, item)
        self.iso__costi14001.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_9.addWidget(self.iso__costi14001, 3, 0, 1, 4)
        self.iso__ente_14001 = QtWidgets.QLineEdit(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iso__ente_14001.sizePolicy().hasHeightForWidth())
        self.iso__ente_14001.setSizePolicy(sizePolicy)
        self.iso__ente_14001.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.iso__ente_14001.setFont(font)
        self.iso__ente_14001.setText("")
        self.iso__ente_14001.setObjectName("iso__ente_14001")
        self.gridLayout_9.addWidget(self.iso__ente_14001, 2, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setStyleSheet("color: #FF0000")
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 2, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: #FF0000")
        self.label_35.setObjectName("label_35")
        self.gridLayout_9.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: #FF0000")
        self.label_33.setObjectName("label_33")
        self.gridLayout_9.addWidget(self.label_33, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setStyleSheet("color: #FF0000")
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 0, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_32 = QtWidgets.QLabel(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: #FF0000")
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 0, 0, 1, 1)
        self.iso__add_date = QtWidgets.QPushButton(self.tab_iso)
        self.iso__add_date.setObjectName("iso__add_date")
        self.gridLayout_7.addWidget(self.iso__add_date, 0, 1, 1, 1)
        self.iso__note = QtWidgets.QTextBrowser(self.tab_iso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iso__note.sizePolicy().hasHeightForWidth())
        self.iso__note.setSizePolicy(sizePolicy)
        self.iso__note.setMaximumSize(QtCore.QSize(1100, 610))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.iso__note.setFont(font)
        self.iso__note.setReadOnly(False)
        self.iso__note.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.iso__note.setOpenExternalLinks(True)
        self.iso__note.setObjectName("iso__note")
        self.gridLayout_7.addWidget(self.iso__note, 1, 0, 1, 2)
        self.gridLayout_10.addLayout(self.gridLayout_7, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tab_iso, "")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(1, 0, 675, 40))
        self.widget.setObjectName("widget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_13 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:#0000FF")
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.cod_impresa = QtWidgets.QLineEdit(self.widget)
        self.cod_impresa.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cod_impresa.sizePolicy().hasHeightForWidth())
        self.cod_impresa.setSizePolicy(sizePolicy)
        self.cod_impresa.setObjectName("cod_impresa")
        self.gridLayout_11.addWidget(self.cod_impresa, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem5, 0, 2, 1, 1)
        self.bt_box = QtWidgets.QDialogButtonBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_box.sizePolicy().hasHeightForWidth())
        self.bt_box.setSizePolicy(sizePolicy)
        self.bt_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_box.setAutoFillBackground(False)
        self.bt_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save)
        self.bt_box.setCenterButtons(False)
        self.bt_box.setObjectName("bt_box")
        self.gridLayout_11.addWidget(self.bt_box, 0, 3, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.cod_impresa, self.imp__ragione_sociale)
        Form.setTabOrder(self.imp__ragione_sociale, self.soa__riferimenti)
        Form.setTabOrder(self.soa__riferimenti, self.imp__codice_fiscale)
        Form.setTabOrder(self.imp__codice_fiscale, self.imp__email)
        Form.setTabOrder(self.imp__email, self.imp__email2)
        Form.setTabOrder(self.imp__email2, self.imp__indirizzo_legale)
        Form.setTabOrder(self.imp__indirizzo_legale, self.imp__comune_legale)
        Form.setTabOrder(self.imp__comune_legale, self.imp__provincia_legale)
        Form.setTabOrder(self.imp__provincia_legale, self.imp__indirizzo_op)
        Form.setTabOrder(self.imp__indirizzo_op, self.imp__comune_op)
        Form.setTabOrder(self.imp__comune_op, self.imp__provincia_op)
        Form.setTabOrder(self.imp__provincia_op, self.imp__tel)
        Form.setTabOrder(self.imp__tel, self.imp__sdi)
        Form.setTabOrder(self.imp__sdi, self.imp__fax)
        Form.setTabOrder(self.imp__fax, self.imp__pec)
        Form.setTabOrder(self.imp__pec, self.imp__website)
        Form.setTabOrder(self.imp__website, self.imp__contatti)
        Form.setTabOrder(self.imp__contatti, self.soa__tipo)
        Form.setTabOrder(self.soa__tipo, self.soa__stato)
        Form.setTabOrder(self.soa__stato, self.soa__scad_qualita)
        Form.setTabOrder(self.soa__scad_qualita, self.soa__ente)
        Form.setTabOrder(self.soa__ente, self.soa__scadenza)
        Form.setTabOrder(self.soa__scadenza, self.bt_attestato_pdf)
        Form.setTabOrder(self.bt_attestato_pdf, self.soa__categorie)
        Form.setTabOrder(self.soa__categorie, self.soa__istruttore)
        Form.setTabOrder(self.soa__istruttore, self.soa__add_date)
        Form.setTabOrder(self.soa__add_date, self.soa__note)
        Form.setTabOrder(self.soa__note, self.soa__contratti)
        Form.setTabOrder(self.soa__contratti, self.iso__tabel)
        Form.setTabOrder(self.iso__tabel, self.iso__ente_9001)
        Form.setTabOrder(self.iso__ente_9001, self.iso__costi9001)
        Form.setTabOrder(self.iso__costi9001, self.iso__ente_14001)
        Form.setTabOrder(self.iso__ente_14001, self.iso__costi14001)
        Form.setTabOrder(self.iso__costi14001, self.iso__ente_18001)
        Form.setTabOrder(self.iso__ente_18001, self.iso__costi18001)
        Form.setTabOrder(self.iso__costi18001, self.iso__note)
        Form.setTabOrder(self.iso__note, self.iso__add_date)
        Form.setTabOrder(self.iso__add_date, self.bt_browser_doc)
        Form.setTabOrder(self.bt_browser_doc, self.tabWidget)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Gestione Imprese - Modifica"))
        self.label.setText(_translate("Form", "Ragione Sociale"))
        self.label_26.setText(_translate("Form", "Sede Operativa"))
        self.label_3.setText(_translate("Form", "Sede Legale"))
        self.imp__ragione_sociale.setText(_translate("Form", "Impresa di prova"))
        self.label_2.setText(_translate("Form", "Codice Fiscale"))
        self.imp__codice_fiscale.setText(_translate("Form", "FBELRI79P28H501Q"))
        self.label_10.setText(_translate("Form", "Tel"))
        self.imp__tel.setText(_translate("Form", "Santa Maria Capua Vetere"))
        self.label_11.setText(_translate("Form", "Fax"))
        self.imp__fax.setText(_translate("Form", "Santa Maria Capua Vetere"))
        self.label_27.setText(_translate("Form", "Sito Web"))
        self.imp__website.setText(_translate("Form", "Santa Maria Capua Vetere"))
        self.imp__provincia_legale.setText(_translate("Form", "RM"))
        self.imp__pec.setText(_translate("Form", "Santa Maria Capua Vetere"))
        self.label_8.setText(_translate("Form", "Comune"))
        self.label_31.setText(_translate("Form", "Email"))
        self.label_12.setText(_translate("Form", "SDI"))
        self.label_6.setText(_translate("Form", "Riferimenti "))
        self.imp__provincia_op.setText(_translate("Form", "RM"))
        self.label_30.setText(_translate("Form", "Pec"))
        self.imp__comune_legale.setText(_translate("Form", "Santa Maria Capua Vetere"))
        self.imp__comune_op.setText(_translate("Form", "Santa Maria Capua Vetere"))
        self.label_4.setText(_translate("Form", "Provincia"))
        self.imp__sdi.setText(_translate("Form", "Santa Maria Capua Vetere"))
        self.imp__email.setText(_translate("Form", "Santa Maria Capua Vetere"))
        self.label_28.setText(_translate("Form", "Comune"))
        self.imp__email2.setText(_translate("Form", "Santa Maria Capua Vetere"))
        self.label_29.setText(_translate("Form", "Provincia"))
        item = self.imp__contatti.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Referente"))
        item = self.imp__contatti.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ruolo"))
        item = self.imp__contatti.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Cell"))
        item = self.imp__contatti.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Email"))
        item = self.imp__contatti.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Altro"))
        self.label_37.setText(_translate("Form", "Contatti"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_generale), _translate("Form", "Generale"))
        self.label_15.setText(_translate("Form", "Tipo"))
        self.soa__tipo.setText(_translate("Form", "A"))
        self.label_14.setText(_translate("Form", "Stato"))
        self.soa__stato.setText(_translate("Form", "B"))
        self.label_18.setText(_translate("Form", "Scadenza Qualità"))
        self.label_17.setText(_translate("Form", "Ente 9001"))
        self.soa__ente.setText(_translate("Form", "poca"))
        self.label_19.setText(_translate("Form", "Scadenza SOA"))
        self.bt_attestato_pdf.setText(_translate("Form", "Attestato PDF"))
        self.label_20.setText(_translate("Form", "Categorie"))
        item = self.soa__categorie.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Cat"))
        item = self.soa__categorie.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Classif"))
        self.label_16.setText(_translate("Form", "Istruttore"))
        self.soa__istruttore.setText(_translate("Form", "Alberto Sordi"))
        self.label_25.setStyleSheet(_translate("Form", "color: #FF0000"))
        self.label_25.setText(_translate("Form", "Note"))
        self.label_21.setText(_translate("Form", "Contratti"))
        item = self.soa__contratti.horizontalHeaderItem(0)
        item.setText(_translate("Form", "firma contr."))
        item = self.soa__contratti.horizontalHeaderItem(1)
        item.setText(_translate("Form", "invio contr."))
        item = self.soa__contratti.horizontalHeaderItem(2)
        item.setText(_translate("Form", "operazione"))
        item = self.soa__contratti.horizontalHeaderItem(3)
        item.setText(_translate("Form", "prezzo"))
        item = self.soa__contratti.horizontalHeaderItem(4)
        item.setText(_translate("Form", "rate"))
        item = self.soa__contratti.horizontalHeaderItem(5)
        item.setText(_translate("Form", "fine pagamento"))
        item = self.soa__contratti.horizontalHeaderItem(6)
        item.setText(_translate("Form", "% nostra"))
        item = self.soa__contratti.horizontalHeaderItem(7)
        item.setText(_translate("Form", "% da dare"))
        item = self.soa__contratti.horizontalHeaderItem(8)
        item.setText(_translate("Form", "dare a..."))
        self.soa__add_date.setText(_translate("Form", "aggiungi data"))
        self.soa__note.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Titolo</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Qualche nota evidente</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_soa), _translate("Form", "SOA"))
        self.label_36.setText(_translate("Form", "Generale"))
        self.bt_browser_doc.setText(_translate("Form", "Browser Documenti"))
        item = self.iso__tabel.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Certificazione"))
        item = self.iso__tabel.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Data"))
        item = self.iso__tabel.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Stato"))
        item = self.iso__tabel.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Tipo"))
        item = self.iso__tabel.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Ente"))
        item = self.iso__tabel.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Consul"))
        item = self.iso__tabel.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Consul + IVA"))
        item = self.iso__tabel.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Incasso Consul"))
        item = self.iso__tabel.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Fatt. Consul"))
        item = self.iso__tabel.horizontalHeaderItem(9)
        item.setText(_translate("Form", "Incasso Ente"))
        item = self.iso__tabel.horizontalHeaderItem(10)
        item.setText(_translate("Form", "Provvig. Ente"))
        self.label_24.setText(_translate("Form", "Ente:"))
        item = self.iso__costi9001.verticalHeaderItem(0)
        item.setText(_translate("Form", "1° Anno"))
        item = self.iso__costi9001.verticalHeaderItem(1)
        item.setText(_translate("Form", "2° Anno"))
        item = self.iso__costi9001.verticalHeaderItem(2)
        item.setText(_translate("Form", "3° Anno"))
        item = self.iso__costi9001.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Consulenza"))
        item = self.iso__costi9001.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ente"))
        item = self.iso__costi9001.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Scadenza"))
        item = self.iso__costi9001.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Consulente"))
        item = self.iso__costi18001.verticalHeaderItem(0)
        item.setText(_translate("Form", "1° Anno"))
        item = self.iso__costi18001.verticalHeaderItem(1)
        item.setText(_translate("Form", "2° Anno"))
        item = self.iso__costi18001.verticalHeaderItem(2)
        item.setText(_translate("Form", "3° Anno"))
        item = self.iso__costi18001.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Consulenza"))
        item = self.iso__costi18001.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ente"))
        item = self.iso__costi18001.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Scadenza"))
        item = self.iso__costi18001.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Consulente"))
        self.label_34.setText(_translate("Form", "Costi ISO 18001"))
        item = self.iso__costi14001.verticalHeaderItem(0)
        item.setText(_translate("Form", "1° Anno"))
        item = self.iso__costi14001.verticalHeaderItem(1)
        item.setText(_translate("Form", "2° Anno"))
        item = self.iso__costi14001.verticalHeaderItem(2)
        item.setText(_translate("Form", "3° Anno"))
        item = self.iso__costi14001.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Consulenza"))
        item = self.iso__costi14001.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ente"))
        item = self.iso__costi14001.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Scadenza"))
        item = self.iso__costi14001.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Consulente"))
        self.label_23.setText(_translate("Form", "Ente:"))
        self.label_35.setText(_translate("Form", "Costi ISO 14001"))
        self.label_33.setText(_translate("Form", "Costi ISO 9001"))
        self.label_22.setText(_translate("Form", "Ente:"))
        self.label_32.setText(_translate("Form", "Note"))
        self.iso__add_date.setText(_translate("Form", "aggiungi data"))
        self.iso__note.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Titolo</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; text-decoration: underline;\">Qualche nota evidente</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_iso), _translate("Form", "ISO"))
        self.label_13.setText(_translate("Form", "Codice impresa"))
        self.cod_impresa.setText(_translate("Form", "32"))


import res_rc
